= SAÉ 3.01 2023-2024
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.

Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné en cours (https://classroom.github.com/a/fePVlfpN).
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/sae3-01-template. En complément du cours Moodle de la SAE 3.01 (cf. <<liensUtiles>>), ce dépôt template vous permet d'accéder à des exemples d'https://github.com/IUT-Blagnac/sae3-01-template/issues[issues], de https://github.com/IUT-Blagnac/sae3-01-template/releases[releases], ou d'autres artefacts à venir.

toc::[]

== Equipe

Projet est réalisé par::
- https://github.com/RayanSellou[Rayan Sellou]
- https://github.com/YannisGibert[Yannis Gibert]
- https://github.com/Marshall331[Ahmad Khalil]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

== Contexte général

TIP: Cette partie de votre `README.adoc` peut être supprimée ou mise ailleurs.

=== Dépôt initial

Ce dépôt initial a été créé pour que tous les groupes de 2ème année aient les mêmes informations de départ.

Vous y trouverez des fichiers qui peuvent être supprimés s'ils ne vous sont pas utiles :

- `.gitignore` => un fichier minimaliste des éléments à ne pas pousser en général sur vos dépôts (utiliser la commande `git add -f` pour forcer l'ajout d'un fichier Jar qui ne bougera plus, pour archive par exemple).
- `.github` => le répertoire qui contient des éléments de gestion de projet :
** `workflows` => le repertoire qui contient les actions à lancer à chaque push sur votre repo. 
*** `blank.yml` => un exemple bidon mais dont vous pourrez vérifier l’exécution correcte (1er tag)
** `ISSUE_TEMPLATE` => le repertoire qui contient quelques templates pour vos issues.
*** `us.yml` => Exemple de template pour les User Stories
*** `bug.yml` => Exemple de template pour les issues de bug report

TIP: Adaptez ces fichiers à votre projet et à votre organisation. Et inspirez-vous en pour en ajouter.

[[liensUtiles]]
=== Liens utiles

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

TIP: Pensez à utiliser les salons Discord dédiés pour poser vos questions.

== Réalisations 

=== Partie IoT

Lien vers le diagramme de séquence système : https://github.com/IUT-Blagnac/sae-3-01-devapp-Groupe-12/blob/master/doc/Notre%20client/Diagrammes/Diagramme%20de%20Séquence%20Système/DSS_exemple_IOT.png[DSS IoT]

Lien vers le use case : https://github.com/IUT-Blagnac/sae-3-01-devapp-Groupe-12/blob/master/doc/Notre%20client/Diagrammes/Use%20Case/US_IOT.png[UC IoT]

==== Partie Python

Lien vers les docs Python : 

Lien vers les tests Python : 

==== Partie Javafx

Lien vers les docs Javafx : 

Lien vers les tests Javafx : 



[cols="1,1"]
|===
|Sprint 1
|
|===


== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

Voici un exemple d'évaluation :

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=935875429&format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=935875429&format=image]
endif::[]

Pensez à effacer du readme tout template inutile et à le mettre à jour avec les informations sur votre équipe. Je n'ai pas soit un scumboard , soit un doc dédié au backlog produit. Du coup où est votre backlog de sprint et les taches(task) à faire ? Pensez à faire un scrumboard par sprint. Je n'ai rien sur les tests (cahier ou fiche à révoir), les docs ne sont pas initialisées (au moins page de garde, sommaire ...), je n'ai pas de release ou au moins par de compte rendu du travail déjà effectué. On est vendredi je n'ai aucune activite depuis plus de 3 jours  de Rayan et Yanis que faites-vous ?!! 

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR653IOTEDovCXjU49qczSZDmK5SBuM43GbpvTrhGCCSAqzpwCdRXU3ey5Y_IRRac1qUnt-iFlPxS5k/pubchart?oid=1287010292&format=interactive"></iframe>
++++
endif::[]
