@startuml
skinparam actorStyle awesome

left to right direction

skinparam actor {
    BackgroundColor DarkSeaGreen
    BorderColor DarkSlateGray
}

actor Client as Client #black
actor Admin as Admin #SkyBlue

rectangle "Utilisateur" {
    usecase "Gérer son compte" as ManageAccount #grey
    usecase "Créer son compte" as CreateAccount #LightCoral
    usecase "Se connecter à son compte" as Login #LightCoral
    usecase "Modifier les informations du compte" as ModifyAccountInfo #LightCoral
    usecase "Suivre ses commandes" as crudOrder #LightCoral
    usecase "Se déconnecter" as Logout #LightCoral

    Client --> ManageAccount
    ManageAccount --> Logout
    ManageAccount --> CreateAccount
    ManageAccount --> Login
    ManageAccount --> ModifyAccountInfo
    ManageAccount --> crudOrder
}

rectangle "Achat" {
    usecase "Acheter" as Purchase #grey
    usecase "Chercher des produits" as SearchProducts #LightSkyBlue
    usecase "Partager des produits sur les réseaux sociaux" as shareProduct #LightSkyBlue
    usecase "Ajouter au panier" as AddToCart #LightSkyBlue
    usecase "Payer sa commande" as payCart #LightSkyBlue
    usecase "Noter un produit" as markProduct #LightSkyBlue

    Client --> Purchase
    Purchase --> SearchProducts
    Purchase --> shareProduct
    Purchase --> AddToCart
    Purchase --> payCart
    Purchase --> markProduct
}

rectangle "Service Client" {
    usecase "Contacter le service client" as customerService #grey

    Client --> customerService
}

rectangle "Administration" {
    usecase "Gérer les produits" as crudProduct #LightGoldenRodYellow
    usecase "Gérer les promotions" as crudPromo #LightGoldenRodYellow
    usecase "Accéder aux statistiques de vente" as showStats #LightGoldenRodYellow

    Admin --> crudProduct
    Admin --> crudPromo
    Admin --> showStats
}
@enduml
